apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-cjzh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-cjzh
    app.kubernetes.io/part-of: tkrw-pr712-0075-0022-app
  name: devfile-sample-cjzh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-cjzh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-cjzh
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0022-tenant/tkrw-pr712-0075-0022-app/devfile-sample-cjzh@sha256:eedc3fe9ea6bafe4f5f3f5d3cbc0fc725b7489af3fb711be30e2e4544a4d2793
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
